spring.application.name=project

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/instagram_clone
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=super-secret-key-minimum-256-bits-for-hs256-algorithm
# 1 day = 86400000 ms
jwt.expiration=86400000